//kurlyDB.js
const kurlyDB = [
    {
        src:'./images/kurly_001.jpg',
        name:'[해태] 여름 시즌 한정 트로피컬 에디션 간식 4종 (택1)',
        summary:'새콤달콤한 여름맛 간식',
        price:3580,
        sale:7,
        review:154,
    },
    {
        src:'./images/kurly_002.jpg',
        name:'[피자로빈슨] 뉴욕 메가 슬라이스 피자 페퍼로니',
        summary:'짭쪼름한 페퍼로니가 듬뿍',
        price:5500,
        sale:20,
        review:18,
    },
    {
        src:'./images/kurly_003.jpg',
        name:'[더반찬] 매콤제육볶음',
        summary:'든든한 한끼 반찬',
        price:7800,
        sale:10,
        review:233,
    },
    {
        src:'./images/kurly_004.jpg',
        name:'[풀무원] 얇은피 꽉찬속 만두 고기왕교자',
        summary:'육즙 가득 고기만두',
        price:4980,
        sale:15,
        review:412,
    },
    {
        src:'./images/kurly_005.jpg',
        name:'[마이셰프] 한우불고기 밀키트 2인분',
        summary:'간편하게 즐기는 정통 불고기',
        price:13900,
        sale:12,
        review:85,
    },
    {
        src:'./images/kurly_006.jpg',
        name:'[브레드이발소] 크로와상 식빵',
        summary:'겹겹이 바삭한 식감',
        price:6200,
        sale:8,
        review:190,
    },
    {
        src:'./images/kurly_007.jpg',
        name:'[자연애찬] 국내산 김치전',
        summary:'바삭하고 고소한 전요리',
        price:4300,
        sale:5,
        review:67,
    },
    {
        src:'./images/kurly_008.jpg',
        name:'[하림] IFF 닭가슴살 오리지널',
        summary:'간편한 고단백 간식',
        price:2600,
        sale:10,
        review:342,
    },
    {
        src:'./images/kurly_009.jpg',
        name:'[청정원] 우리쌀 떡볶이 밀키트',
        summary:'쫀득한 떡과 매콤한 소스',
        price:4900,
        sale:13,
        review:128,
    },
    {
        src:'./images/kurly_010.jpg',
        name:'[삼양] 불닭마요 소스',
        summary:'매콤한 중독의 맛',
        price:3200,
        sale:9,
        review:76,
    },
    {
        src:'./images/kurly_011.jpg',
        name:'[오뚜기] 진라면 매운맛 5입',
        summary:'언제 먹어도 맛있는 라면',
        price:3880,
        sale:6,
        review:245,
    },
    {
        src:'./images/kurly_012.jpg',
        name:'[빙그레] 바나나맛우유 4입',
        summary:'달콤한 추억의 맛',
        price:4200,
        sale:5,
        review:198,
    },
]